- hosts: all
  become: yes
  tasks:
    - name: Fetch files
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: "{{ item }}"
      fail_on_missing: no
      loop:
        - /etc/fstab
        - /etc/sudoers
        - /etc/sssd/sssd.conf
        - /etc/samba/smb.conf
