- hosts: all
  become: yes
  tasks:
    - name: Fetch files
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: ~/ryacom-configs/{{ ansible_fqdn }}/{{ item }}
        flat: yes
      loop:
        - /etc/fstab
        - /etc/sudoers
        - /etc/realmd.conf
        - /etc/samba/smb.conf
