- hosts: all
  become: yes
  tasks:
  - name: Update all installed packages
    dnf:
      name: '*'
      state: latest
      #update_cache: yes
      #update_only: yes
    register: dnf_update_status

  #- name: Remove old packages
  #  dnf:
  #    autoremove: yes

  - name: Reboot if packages were updated
    reboot:
    when: dnf_update_status.changed
