- hosts: all
  become: yes
  tasks:
  - name: Install Zabbix repo
    dnf:
      name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
      state: present
      disable_gpg_check: yes
      
  - name: Clear dnf cache
    command: dnf clean all
      
  - name: Install packages
    dnf:
        name:
          - zabbix-agent
        state: present
        
  - name: Set Zabbix server IP address in agent config
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "^Server=127.0.0.1"
        line: Server=zabbix.ad.ryacom.org
        
  - name: Start and enable Zabbix agent
    service:
      name: zabbix-agent
      state: restarted
      enabled: yes
