- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install Zabbix repo
    dnf:
      name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
      state: present
      disable_gpg_check: yes
      
  - name: Clear dnf cache
    command: dnf clean all
      
  - name: Install packages
    dnf:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-selinux-policy
          - zabbix-agent
          - mysql-server
          - python3-pip
        state: present
        
  - name: Install pip modules
    pip:
      name:
        - PyMySQL
      state: present
      executable: pip3      
        
  - name: Start and enable MySQL
    service:
      name: mysqld
      state: started
      enabled: yes
        
  - name: Create Zabbix database
    community.mysql.mysql_db: login_user=root login_password="" name=zabbix state=present encoding=utf8mb4 collation=utf8mb4_bin
      
  - name: Create Zabbix MySQL user
    community.mysql.mysql_user: login_user=root login_password="" name=zabbix password="password" priv="zabbix.*:ALL" state=present
      
  - name: Import initial Zabbix data
    shell: zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql --user=zabbix --password=password
      
  - name: Edit Zabbix DB password in config
    lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: "^# DBpassword="
      line: DBPassword=password
        
  - name: Start and enable Zabbix server
    service:
      name: zabbix-server
      state: restarted
      enabled: yes
      
  - name: Start and enable Zabbix agent
    service:
      name: zabbix-agent
      state: restarted
      enabled: yes

  - name: Start and enable httpd
    service:
      name: httpd
      state: restarted
      enabled: yes

  - name: Start and enable php-fpm
    service:
      name: php-fpm
      state: restarted
      enabled: yes
        
  - name: Add HTTP firewall rule
    firewalld:
      service: http
      permanent: yes
      state: enabled
        
  - name: Add HTTPS firewall rule
    firewalld:
      service: https
      permanent: yes
      state: enabled
        
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
      enabled: yes
    
  - name: Print URL
    debug:
      msg: http://hostname/zabbix Admin/zabbix
